### PR TITLE
bump: sev crate to 3.1.1

### PR DESCRIPTION
**Pull request by wobito**
# Bump SEV crate
This PR will bump the SEV crate to 3.1.1 for use within the github.com/confidential-containers/trustee and github.com/confidential-containers/guest-compoments repos

### CODE REVIEW

**Review by mkulke — COMMENTED** [review]
In general that should work, can you do the following?

- do a drive-by fix for the lint
- run "cargo semver-check" to tell if there's a breaking change, since we might expose some sev types
- bump the version accordingly (patch for non-breaking, minor for breaking).

**Comment by wobito** [comment]
Results from `cargo semver-checks`

```
Parsing az-cvm-vtpm v0.5.2 (current)
      Parsed [   9.601s] (current)
     Parsing az-cvm-vtpm v0.5.2 (baseline)
      Parsed [   9.377s] (baseline)
    Checking az-cvm-vtpm v0.5.2 -> v0.5.2 (no change)
     Checked [   0.007s] 72 checks; 72 passed, 0 unnecessary
    Finished [  18.995s] az-cvm-vtpm
```

**Review by mkulke — APPROVED** [review]
lgtm. thanks, I'll publish a release.

**Comment by mkulke** [comment]
> lgtm. thanks, I'll publish a release.

@wobito crates have been published

**Pull request merged**
